# Generated by Django 5.1.2 on 2024-11-28 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
