# Generated by Django 5.1.2 on 2024-11-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_researchproject_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='project_type',
            field=models.CharField(choices=[('research', 'Research'), ('development', 'Development'), ('analysis', 'Analysis'), ('other', 'Other')], default='research', max_length=20),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
    ]
