# Generated by Django 5.1.2 on 2024-11-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_researchproject_project_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='file',
        ),
    ]
