# Generated by Django 5.1.2 on 2024-11-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_researchproject_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
    ]
