# Generated by Django 5.1.2 on 2024-11-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('users', '0003_profile_department_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='data',
            field=models.FileField(upload_to='data_collections/'),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.participant'),
        ),
    ]
