# Generated by Django 5.1.2 on 2024-11-29 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_datacollection_data_and_more'),
        ('project', '0005_researchproject_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_data_collections', to='project.researchproject'),
        ),
    ]
