# Generated by Django 5.0.6 on 2024-07-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermarketsales',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='supermarketsales',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='supermarketsales',
            name='customer_type_id',
        ),
        migrations.RemoveField(
            model_name='supermarketsales',
            name='gender_id',
        ),
        migrations.RemoveField(
            model_name='supermarketsales',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='supermarketsales',
            name='productline_id',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='CustomerType',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ProductLine',
        ),
        migrations.DeleteModel(
            name='SuperMarketSales',
        ),
    ]
